#!/bin/bash

set -e
pkg=ourgrid-worker-vbox

# Adds buddycloud user
#if [ "$1" = "configure" ]; then
#    adduser --system --quiet --group --disabled-password \
#        --gecos "ourgrid sys account" \
#        --no-create-home --home "/var/run/$pkg" \
#        ourgrid
#fi

#DEBHELPER#
