#!/bin/bash

set -e
pkg=ourgrid-worker-vbox

min() {
  if [ "$1" -gt "$2" ]; then
    echo "$2"
  else
    echo "$1"
  fi
}

total_memory() {
  NUM_WORKERS="$1"
  TOTAL_MEM=`grep MemTotal /proc/meminfo | awk '{print $2}'`
  SO_MEM=`expr 512 \* 1024`
  ALLOCABLE_MEM=$(echo "($TOTAL_MEM / 1024 * 0.65)" | bc -l)
  ALLOCABLE_MEM_INT=$(echo $ALLOCABLE_MEM | sed -e "s/\(\.[0-9]\).*//g")
  if [ $NUM_WORKERS -gt 1 ]; then
    WORKER_MEM=$(echo "($ALLOCABLE_MEM * 1.35) / $NUM_WORKERS" | bc -l)
    WORKER_MEM_INT=$(echo $WORKER_MEM | sed -e "s/\(\.[0-9]\).*//g")
    echo $WORKER_MEM_INT
  else
    echo $ALLOCABLE_MEM_INT
  fi
}

memory() {
  TOTAL_MEM=`grep MemTotal /proc/meminfo | awk '{print $2}'`
  SO_MEM=`expr 512 \* 1024`
  ALLOCABLE_MEM=`expr $TOTAL_MEM - $SO_MEM`
  VM_MEM=`expr 256 \* 1024`
  NUM_WORKERS_BY_MEM=`expr $ALLOCABLE_MEM / $VM_MEM`
  echo $NUM_WORKERS_BY_MEM
}

space_available() {
  DEVICE=`df -P /etc | tail -1 | cut -d' ' -f 1`
  SPACE_AVAILABLE=`df -B 1073741824 | grep -w $DEVICE | awk '{print $4}'`
  NUM_WORKERS_BY_SPACE=`expr $SPACE_AVAILABLE / 10`
  echo $NUM_WORKERS_BY_SPACE
}

number_of_cores() {
  NUM_OF_PROCESSORS=`grep -c processor /proc/cpuinfo`
  echo $NUM_OF_PROCESSORS
}

# Get space available
NUMBER_OF_WORKERS_BY_SPACE=$(space_available)

# Get number of processors
NUMBER_OF_PROCESSORS=$(number_of_cores)

# Get number of workers by memory
NUM_OF_WORKERS_BY_MEM=$(memory)

# Recommend a number of workers
MIN_TEMP=$(min $NUMBER_OF_WORKERS_BY_SPACE $NUMBER_OF_PROCESSORS)
RECOMMENDED_NUM_WORKERS=$(min $MIN_TEMP $NUM_OF_WORKERS_BY_MEM)

NUM_WORKERS=$RECOMMENDED_NUM_WORKERS
USERNAME="$HOSTNAME"
SERVERNAME="xmpp.ourgrid.org"
PASSWORD="xmpp-password"
PEERADDRESS="lsd-voluntary-peer@xmpp.ourgrid.org"
IDLENESS_DETECTOR=Yes
IDLENESS_TIME=1200

VM_NAME="vm-"$USERNAME
INSTALLATION_DIR="/etc/ourgrid"
VM_IMAGES_DIR=$INSTALLATION_DIR/vbox_images
IMAGE_NAME="og-image"
IMAGE_DOWNLOADED_FILE="$IMAGE_NAME.tar.gz"

#Download VBOX_IMAGE
echo
echo "================================================="
echo "  Downloading VirtualBox embedded ..."
echo "================================================="

wget -nc -P $INSTALLATION_DIR http://www2.lsd.ufcg.edu.br/~marcosancj/vbox-bin.tar.gz
cd $INSTALLATION_DIR
tar -xzf vbox-bin.tar.gz
rm vbox-bin.tar.gz

#Download VBOX_IMAGE
echo
echo "================================================="
echo "  Downloading OurGrid Worker VirtualBox image ..."
echo "================================================="

wget -nc -P $VM_IMAGES_DIR http://maven.ourgrid.org/repos/linux/vbox/linux-vbox/og-image.vdi

/bin/bash copyworkers-vbox "$NUM_WORKERS" "$USERNAME" "$SERVERNAME" "$PASSWORD" "$PEERADDRESS" "$IMAGE_FILE"

if [ -e /etc/ourgrid/vmnames.conf ] ; then
	deleteWorkerVMs /etc/ourgrid/vmnames.conf vbox
	rm -f /etc/ourgrid/vmnames.conf
fi

TOTAL_MEM=$(total_memory $NUM_WORKERS)

for WORKER_NUM in $(seq 1 $NUM_WORKERS)
do
	echo
	echo "==========================="
	echo "  Configuring Worker $WORKER_NUM  "
	echo "==========================="
	
	WORKER_BASE="/etc/ourgrid/worker-vbox"$WORKER_NUM
	WORKER_PROPERTIES=$WORKER_BASE"/worker.properties"
	
	#VM CONFIGURATIONS
	echo "vm.os.version=Ubuntu" >> $WORKER_PROPERTIES
	echo "worker.executor=GENERIC" >> $WORKER_PROPERTIES
	echo "vm.hypervisor.type=VBOXSDK" >> $WORKER_PROPERTIES
	echo "vm.disk.type=sata" >> $WORKER_PROPERTIES
	echo "vm.os=linux" >> $WORKER_PROPERTIES
	echo "vm.memory=$TOTAL_MEM" >> $WORKER_PROPERTIES
	echo "vm.password=worker" >> $WORKER_PROPERTIES
	echo "vm.user=worker" >> $WORKER_PROPERTIES
	echo "vm.start.timeout=120" >> $WORKER_PROPERTIES
	echo "vm.networkadaptername=jitvmnet0" >> $WORKER_PROPERTIES
	echo "vm.networktype=host-only" >> $WORKER_PROPERTIES
	
	echo "vm.name=""$VM_NAME"_"$WORKER_NUM" >> $WORKER_PROPERTIES
	echo $VM_NAME"_"$WORKER_NUM >> /etc/ourgrid/vmnames.conf
	
	NEW_DISK_PATH="$VM_IMAGES_DIR/$IMAGE_NAME"_"$(hostname)"_"$WORKER_NUM".vdi
	echo "vm.disk.path=""$NEW_DISK_PATH" >> $WORKER_PROPERTIES
	
	#clone image
	if [ ! -e "$NEW_DISK_PATH" ] ; then
		if [ -e "$VM_IMAGES_DIR/$IMAGE_NAME".vdi ] ; then
			ourvirt -m clone -h vboxsdk -source "$VM_IMAGES_DIR/$IMAGE_NAME".vdi -target "$NEW_DISK_PATH"
		else
			echo "Error while cloning vbox image."
			exit 1
		fi
	fi
	
	#IDLENESS DETECTOR
	if echo $IDLENESS_DETECTOR | egrep -q Yes 
	then
		echo "worker.idlenessdetector=yes" >> $WORKER_PROPERTIES
		echo "worker.idlenesstime="$IDLENESS_TIME >> $WORKER_PROPERTIES
	fi
	
	#create brokers storage folder
	STORAGE_FOLDER="/etc/ourgrid/worker-vbox"$WORKER_NUM"/.brokerstorage"
	echo "worker.storagedir=""$STORAGE_FOLDER" >> $WORKER_PROPERTIES
	mkdir -p $STORAGE_FOLDER
	chmod -R 777 $STORAGE_FOLDER
done


chmod +x /etc/init.d/worker-vbox
update-rc.d worker-vbox defaults 

chown ourgrid /usr/bin/worker
#chown ourgrid /usr/bin/testjvm
#chown -R ourgrid /usr/share/ourgrid
chown -R ourgrid /etc/ourgrid
chmod +s /etc/ourgrid/vbox-bin/jitvmutil/jitvmutil
export VBOX_HOME=/etc/ourgrid/vbox-bin/vbox_home
VBOX_BIN_HOME=/etc/ourgrid/vbox-bin
cd $VBOX_BIN_HOME
sudo ln -s $VBOX_BIN_HOME/src /usr/src/jitvmhost-4.2.5
sudo bash vboxdrv.sh.in setup
$VBOX_BIN_HOME/jitvmutil/jitvmutil modup
$VBOX_BIN_HOME/VBoxManage hostonlyif create
$VBOX_BIN_HOME/VBoxManage hostonlyif ipconfig jitvmnet0 --ip 192.168.52.1 --netmask 255.255.255.0
$VBOX_BIN_HOME/VBoxManage dhcpserver add --ifname jitvmnet0 --ip 192.168.52.1 --netmask 255.255.255.0 --lowerip 192.168.52.101 --upperip 192.168.52.254 --enable
$VBOX_BIN_HOME/jitvmutil/jitvmutil ifup jitvmnet0
$VBOX_BIN_HOME/jitvmutil/jitvmutil ifaddress jitvmnet0 192.168.52.100

rm -f /usr/bin/copyworkers-vbox
rm -f "$VM_IMAGES_DIR/$IMAGE_NAME".vdi

#DEBHELPER#
