#!/bin/bash

set -e
pkg=ourgrid-worker

min() {
  if [ "$1" -gt "$2" ]; then
    echo "$2"
  else
    echo "$1"
  fi
}

max() {
  if [ "$1" -lt "$2" ]; then
    echo "$2"
  else
    echo "$1"
  fi
}

total_memory() {
  NUM_WORKERS="$1"
  TOTAL_MEM=`grep MemTotal /proc/meminfo | awk '{print $2}'`
  SO_MEM=`expr 512 \* 1024`
  ALLOCABLE_MEM=$(echo "($(expr $TOTAL_MEM - $SO_MEM) / 1024 * 0.65)" | bc -l)
  ALLOCABLE_MEM_INT=$(echo $ALLOCABLE_MEM | sed -e "s/\(\.[0-9]\).*//g")
  if [ $NUM_WORKERS -gt 1 ]; then
    WORKER_MEM=$(echo "($ALLOCABLE_MEM * 1.35) / $NUM_WORKERS" | bc -l)
    WORKER_MEM_INT=$(echo $WORKER_MEM | sed -e "s/\(\.[0-9]\).*//g")
    echo $WORKER_MEM_INT
  else
    echo $ALLOCABLE_MEM_INT
  fi
}

memory() {
  TOTAL_MEM=`grep MemTotal /proc/meminfo | awk '{print $2}'`
  SO_MEM=`expr 512 \* 1024`
  ALLOCABLE_MEM=`expr $TOTAL_MEM - $SO_MEM`
  VM_MEM=`expr 128 \* 1024`
  NUM_WORKERS_BY_MEM=`expr $ALLOCABLE_MEM / $VM_MEM`
  echo $NUM_WORKERS_BY_MEM
}

space_available() {
  DEVICE=`df -P /etc | tail -1 | cut -d' ' -f 1`
  SPACE_AVAILABLE=`df -P -B 1073741824 | grep -w $DEVICE | awk '{print $4}'`
  NUM_WORKERS_BY_SPACE=`expr $SPACE_AVAILABLE / 1`
  echo $NUM_WORKERS_BY_SPACE
}

number_of_cores() {
  NUM_OF_PROCESSORS=`grep -c processor /proc/cpuinfo`
  echo $NUM_OF_PROCESSORS
}

# Get space available
NUMBER_OF_WORKERS_BY_SPACE=$(space_available)

# Get number of processors
NUMBER_OF_PROCESSORS=$(number_of_cores)

# Get number of workers by memory
NUM_OF_WORKERS_BY_MEM=$(memory)

# Recommend a number of workers
MIN_TEMP=$(min $NUMBER_OF_WORKERS_BY_SPACE $NUMBER_OF_PROCESSORS)
MIN_RECOMMENDED_NUM_WORKERS=$(min $MIN_TEMP $NUM_OF_WORKERS_BY_MEM)
RECOMMENDED_NUM_WORKERS=$(max 1 $MIN_RECOMMENDED_NUM_WORKERS)

NUM_WORKERS=$RECOMMENDED_NUM_WORKERS

USERNAME="$HOSTNAME"
SERVERNAME="xmpp.ourgrid.org"
PASSWORD="xmpp-password"
PEERADDRESS="lsd-voluntary-peer@xmpp.ourgrid.org"
IDLENESS_DETECTOR=Yes
IDLENESS_TIME=1200

CPU_ARCH=`uname -m`
CPU_X86_64_ARCH=x86_64

/bin/bash copyworkers "$NUM_WORKERS" "$USERNAME" "$SERVERNAME" "$PASSWORD" "$PEERADDRESS" "$IDLENESS_DETECTOR" "$IDLENESS_TIME"

TOTAL_MEM=$(total_memory $NUM_WORKERS)

for WORKER_NUM in $(seq 1 $NUM_WORKERS)
do
	echo
	echo "==========================="
	echo "  Configuring Worker $WORKER_NUM  "
	echo "==========================="
	
	#IDLENESS DETECTOR
	if echo $IDLENESS_DETECTOR | egrep -q Yes 
	then
		echo "worker.idlenessdetector=yes" >> $WORKER_PROPERTIES
		echo "worker.idlenesstime="$IDLENESS_TIME >> $WORKER_PROPERTIES
	fi
	
	#create brokers storage folder
	STORAGE_FOLDER="/etc/ourgrid/worker"$WORKER_NUM"/.brokerstorage"
	echo "worker.storagedir=""$STORAGE_FOLDER" >> $WORKER_PROPERTIES
	mkdir -p $STORAGE_FOLDER
	chmod -R 777 $STORAGE_FOLDER
	
	#create playpen root folder
	PLAYPEN_ROOT_FOLDER="/etc/ourgrid/worker"$WORKER_NUM"/.playpenroot"
	echo "worker.playpenroot=""$PLAYPEN_ROOT_FOLDER" >> $WORKER_PROPERTIES
	mkdir -p $PLAYPEN_ROOT_FOLDER
	chmod -R 755 $PLAYPEN_ROOT_FOLDER
	chown -R ourgrid:ourgrid $PLAYPEN_ROOT_FOLDER
done

mv /etc/ourgrid/init.d/worker /etc/init.d/
rm -rf /etc/ourgrid/init.d
chmod +x /etc/init.d/worker
chmod +x /etc/ourgrid/bin/worker-core
chkconfig --add worker

chown root:root /usr/share/ourgrid/idleness
chmod 4755 /usr/share/ourgrid/idleness

# Creating log directory and changing owner to OurGrid
mkdir -p /var/log/ourgrid
chown -R ourgrid:ourgrid /var/log/ourgrid

mkdir /var/run/ourgrid
chown -R ourgrid:ourgrid /var/run/ourgrid

chown ourgrid /usr/bin/worker
chown -R ourgrid /etc/ourgrid

rm -f /usr/bin/copyworkers
#DEBHELPER#