#!/bin/bash

set -e
pkg=ourgrid-worker-qemu

min() {
  if [ "$1" -gt "$2" ]; then
    echo "$2"
  else
    echo "$1"
  fi
}

total_memory() {
  NUM_WORKERS="$1"
  TOTAL_MEM=`grep MemTotal /proc/meminfo | awk '{print $2}'`
  SO_MEM=`expr 512 \* 1024`
  ALLOCABLE_MEM=$(echo "($(expr $TOTAL_MEM - $SO_MEM) / 1024 * 0.65)" | bc -l)
  ALLOCABLE_MEM_INT=$(echo $ALLOCABLE_MEM | sed -e "s/\(\.[0-9]\).*//g")
  if [ $NUM_WORKERS -gt 1 ]; then
    WORKER_MEM=$(echo "($ALLOCABLE_MEM * 1.35) / $NUM_WORKERS" | bc -l)
    WORKER_MEM_INT=$(echo $WORKER_MEM | sed -e "s/\(\.[0-9]\).*//g")
    echo $WORKER_MEM_INT
  else
    echo $ALLOCABLE_MEM_INT
  fi
}

memory() {
  TOTAL_MEM=`grep MemTotal /proc/meminfo | awk '{print $2}'`
  SO_MEM=`expr 512 \* 1024`
  ALLOCABLE_MEM=`expr $TOTAL_MEM - $SO_MEM`
  VM_MEM=`expr 128 \* 1024`
  NUM_WORKERS_BY_MEM=`expr $ALLOCABLE_MEM / $VM_MEM`
  echo $NUM_WORKERS_BY_MEM
}

space_available() {
  DEVICE=`df -P /etc | tail -1 | cut -d' ' -f 1`
  SPACE_AVAILABLE=`df -B 1073741824 | grep -w $DEVICE | awk '{print $4}'`
  NUM_WORKERS_BY_SPACE=`expr $SPACE_AVAILABLE / 10`
  echo $NUM_WORKERS_BY_SPACE
}

number_of_cores() {
  NUM_OF_PROCESSORS=`grep -c processor /proc/cpuinfo`
  echo $NUM_OF_PROCESSORS
}

# Get space available
NUMBER_OF_WORKERS_BY_SPACE=$(space_available)

# Get number of processors
NUMBER_OF_PROCESSORS=$(number_of_cores)

# Get number of workers by memory
NUM_OF_WORKERS_BY_MEM=$(memory)

# Recommend a number of workers
MIN_TEMP=$(min $NUMBER_OF_WORKERS_BY_SPACE $NUMBER_OF_PROCESSORS)
RECOMMENDED_NUM_WORKERS=$(min $MIN_TEMP $NUM_OF_WORKERS_BY_MEM)

NUM_WORKERS=$RECOMMENDED_NUM_WORKERS
USERNAME="$HOSTNAME"
SERVERNAME="xmpp.ourgrid.org"
PASSWORD="xmpp-password"
PEERADDRESS="lsd-voluntary-peer@xmpp.ourgrid.org"
IDLENESS_DETECTOR=Yes
IDLENESS_TIME=1200

VM_NAME="vm-"$USERNAME
INSTALLATION_DIR="/etc/ourgrid"
VM_IMAGES_DIR=$INSTALLATION_DIR/qemu_images
IMAGE_NAME="og-image"
IMAGE_DOWNLOADED_FILE="$IMAGE_NAME.tar.gz"

echo
echo "================================================="
echo "  Downloading QEMU ..."
echo "================================================="

QEMU_HOME=$INSTALLATION_DIR/qemu
wget -nc -P $QEMU_HOME http://www2.lsd.ufcg.edu.br/~marcosancj/qemu.tar.gz
cd $QEMU_HOME
tar -xzf qemu.tar.gz
rm -f $QEMU_HOME/qemu.tar.gz

echo
echo "================================================="
echo "  Downloading OurGrid Worker QEMU image ..."
echo "================================================="

wget -nc -P $VM_IMAGES_DIR http://www2.lsd.ufcg.edu.br/~marcosancj/ubuntu-lts.qcow2

/bin/bash copyworkers-qemu "$NUM_WORKERS" "$USERNAME" "$SERVERNAME" "$PASSWORD" "$PEERADDRESS" "$IMAGE_FILE"

TOTAL_MEM=$(total_memory $NUM_WORKERS)

for WORKER_NUM in $(seq 1 $NUM_WORKERS)
do
	echo
	echo "==========================="
	echo "  Configuring Worker $WORKER_NUM  "
	echo "==========================="
	
	WORKER_BASE="/etc/ourgrid/worker-qemu"$WORKER_NUM
	WORKER_PROPERTIES=$WORKER_BASE"/worker.properties"
	
	#VM CONFIGURATIONS
	echo "vm.os.version=Ubuntu" >> $WORKER_PROPERTIES
	echo "worker.executor=GENERIC" >> $WORKER_PROPERTIES
	echo "vm.hypervisor.type=QEMU" >> $WORKER_PROPERTIES
	echo "vm.disk.type=sata" >> $WORKER_PROPERTIES
	echo "vm.os=linux" >> $WORKER_PROPERTIES
	echo "vm.memory=$TOTAL_MEM" >> $WORKER_PROPERTIES
	echo "vm.password=reverse" >> $WORKER_PROPERTIES
	echo "vm.user=ubuntu" >> $WORKER_PROPERTIES
	echo "vm.start.timeout=240" >> $WORKER_PROPERTIES
	echo "vm.networktype=host-only" >> $WORKER_PROPERTIES
	
	echo "vm.name=""$VM_NAME"_"$WORKER_NUM" >> $WORKER_PROPERTIES
	
	NEW_DISK_PATH="$VM_IMAGES_DIR/ubuntu-lts.qcow2"
	echo "vm.disk.path=""$NEW_DISK_PATH" >> $WORKER_PROPERTIES
	
	#IDLENESS DETECTOR
	if echo $IDLENESS_DETECTOR | egrep -q Yes 
	then
		echo "worker.idlenessdetector=yes" >> $WORKER_PROPERTIES
		echo "worker.idlenesstime="$IDLENESS_TIME >> $WORKER_PROPERTIES
	fi
	
	#create brokers storage folder
	STORAGE_FOLDER="/etc/ourgrid/worker-qemu"$WORKER_NUM"/.brokerstorage"
	echo "worker.storagedir=""$STORAGE_FOLDER" >> $WORKER_PROPERTIES
	mkdir -p $STORAGE_FOLDER
	chmod -R 777 $STORAGE_FOLDER
	
	#create playpen root folder
	PLAYPEN_ROOT_FOLDER="/etc/ourgrid/worker-qemu"$WORKER_NUM"/.playpenroot"
	echo "worker.playpenroot=""$PLAYPEN_ROOT_FOLDER" >> $WORKER_PROPERTIES
	mkdir -p $PLAYPEN_ROOT_FOLDER
	chmod -R 755 $PLAYPEN_ROOT_FOLDER
	chown -R ourgrid:ourgrid $PLAYPEN_ROOT_FOLDER
done


chmod +x /etc/init.d/worker-qemu
chmod +x /etc/ourgrid/bin/worker-core
update-rc.d worker-qemu defaults

#Installing files for idleness detector
CPU_ARCH=`uname -m`
CPU_x86_64_ARCH=x86_64
tar -xvf /etc/ourgrid/xprintidle.tar.gz -C /etc/ourgrid/
if [ $CPU_ARCH == $CPU_X86_64_ARCH ]; then 
	mv /etc/ourgrid/xprintidle-x86_64 /etc/ourgrid/bin/xprintidle
	rm /etc/ourgrid/xprintidle-i386
else
	mv /etc/ourgrid/xprintidle-i386 /etc/ourgrid/bin/xprintidle
	rm /etc/ourgrid/xprintidle-x86_64
fi

rm /etc/ourgrid/xprintidle.tar.gz
touch /etc/ourgrid/idleness
chmod 777 /etc/ourgrid/idleness
chmod +x /etc/ourgrid/bin/xprintidle
chmod +x /etc/X11/Xsession.d/99ourgrid-worker-idleness

# Creating log directory and changing owner to OurGrid
mkdir -p /var/log/ourgrid
chown -R ourgrid:ourgrid /var/log/ourgrid

mkdir /var/run/ourgrid
chown -R ourgrid:ourgrid /var/run/ourgrid

chown ourgrid /usr/bin/worker
chown -R ourgrid /etc/ourgrid

rm -f /usr/bin/copyworkers-vbox
rm -f "$VM_IMAGES_DIR/$IMAGE_NAME".vdi

#DEBHELPER#
