#!/bin/bash

set -e
pkg=ourgrid-commons

# Adds ourgrid user
if [ "$1" = "configure" ]; then
    adduser --system --quiet --group --disabled-password \
        --gecos "ourgrid sys account" \
        --home "/var/run/$pkg" \
        ourgrid || true
fi

#DEBHELPER#
